### PR TITLE
Removed all mention of Goerli and all associated packages

### LINKED ISSUE #186: Remove support for Goerli Network
## Issue Overview

Currently the framework still shows support for `Goerli` Network.

## Proposed Solutions or Ideas

Clean and remove everything related to `Goerli` testnet without affecting the current performance of framework on devnet or testnet. It could include entire files that the framework is not using anymore.

### Instructions for Contributing

- Leave a comment on this Issue.
- Wait for our confirmation to start on the project.
- Once you have received confirmation, begin working on your contribution.

### Incentives

Contributions are rewarded via Only Dust.

### Contact

For questions, join to our [tg group](https://t.me/+wO3PtlRAreo4MDI9) and reach out our team

### PR DESCRIPTION
**Pull request by Ugo-X**
# Remove support for Goerli Network #186

Fixes #186 

## Types of change

- [ ] Feature
- [x] Bug
- [ ] Enhancement

### CODE REVIEW

**Comment by Nadai2010** [comment]
Hello @Ugo-X , good job everything is correct on my part, the only thing that the changes in "deployedContracts.ts" and "localhost.accounts.json" should not be changed. They are autogenerated and discarded to maintain the original.

**Comment by Ugo-X** [comment]
> Hello @Ugo-X , good job everything is correct on my part, the only thing that the changes in "deployedContracts.ts" and "localhost.accounts.json" should not be changed. They are autogenerated and discarded to maintain the original.

Hello, good afternoon. I just effected the requested changes.

**Comment by Nadai2010** [comment]
I think everything is correct, I only have a doubt about the `localhost.accounts.json`, I think it can be eliminated completely, although `Goerli` is released, the devnet accounts are released, I think it is no longer necessary with the new updates we have thrown out.

@jrcarlos2000  or @edulanasca may affirm this.

The rest I see everything ok

**Comment by Ugo-X** [comment]
alright, so I should delete the file totally?

**Comment by Nadai2010** [comment]
I think so, wait for confirmation from @jrcarlos2000 or @edulanasca to be sure

**Comment by edulanasca** [comment]
@jrcarlos2000 can we have `localhost.accounts.json` deleted, I also noticed that file is not being used at least in the code.

**Comment by edulanasca** [comment]
@Ugo-X you can run `yarn next:lint && yarn next:check-types && yarn format && yarn format:check` to have the workflow pass. Check format step has failed

**Comment by gianalarcon** [comment]
Thanks for your contribution @Ugo-X please check the CI checks

**Comment by edulanasca** [comment]
@Ugo-X you can delete `localhost.accounts.json` as I have confirmed is no longer necessary

**Comment by Ugo-X** [comment]
> @Ugo-X you can delete `localhost.accounts.json` as I have confirmed is no longer necessary

already deleted it in this update i just pushed

**Pull request merged**
