### PR TITLE
chore(v3): update dependencies

### LINKED ISSUE #262: Release v0.3 - Starknet React v3 + Starknet Js v6.12.1
## Issue Overview

Update the versions of the stack mainly to support newer RPC versions and new Cairo versions. Some of the features we want to support are : forking on devnet 0.0.5.

Current versions :
    "@starknet-react/chains": "^0.1.7",
    "@starknet-react/core": "^2.8.2",
    "starknet": "6.7.0",

We need to update to use `@next` version of `starknet-react`  which currently uses[ starknet.js@6.12.1](https://github.com/apibara/starknet-react/blob/f5e1bd9a95c178b05966695f3b3bb25cb5607e38/packages/core/package.json#L48) , besides update the devnet version to support [`0.1.2`](https://github.com/0xSpaceShard/starknet-devnet-rs/releases/tag/v0.1.2)

## Proposed Solutions or Ideas

- take into account that there are shared dependencies between packages such as `starknet.js` , should be updated on both sides/

### PR DESCRIPTION
**Pull request by metalboyrick**
# Task name here

Fixes #262 

## Types of change

- [ ] Feature
- [ ] Bug
- [x] Enhancement

### CODE REVIEW

**Comment by metalboyrick** [comment]
Used starknet `6.12.1`. Reason is that`next` version points to `6.13.0`, which causes the following error with `starknet-react` v3, thoughts? @jrcarlos2000 

image

**Comment by metalboyrick** [comment]
Not sure what is meant by "besides update the devnet version to support [0.1.2](https://github.com/0xSpaceShard/starknet-devnet-rs/releases/tag/v0.1.2)", will mark as ready for review for now. So far smoke testing looks good

**Review by 0xquantum3labs — APPROVED** [review]

**Comment by jrcarlos2000** [comment]
> Used starknet `6.12.1`. Reason is that`next` version points to `6.13.0`, which causes the following error with `starknet-react` v3, thoughts? @jrcarlos2000
> 
> image

Not sure what this issue is about but we can keep the version : `6.12.1` for now. since is the one they have on `main` branch.

**Comment by jrcarlos2000** [comment]
> Not sure what is meant by "besides update the devnet version to support [0.1.2](https://github.com/0xSpaceShard/starknet-devnet-rs/releases/tag/v0.1.2)", will mark as ready for review for now. So far smoke testing looks good

i would say this is more like a README, local update of your devnet version.

**Comment by 0xquantum3labs** [comment]
for now is good lets keep this versions.

**Pull request merged**
