### PR TITLE
Fix correctly display wallet connectors

### LINKED ISSUE #156: Correctly display available wallet connectors
## Issue Overview

Currently burner wallet connector can be used only on `devnet`, however when connected on sepolia or mainnet, it  still shows up. 
image
likewise, block burner wallet connector from 
## Proposed Solutions or Ideas

Move connectors out of [`ScaffoldStarkAppWithProviders`](https://github.com/Quantum3-Labs/scaffold-stark-2/blob/bb59cf4e0cfe0b4881104368288a1b5447224787/packages/nextjs/components/ScaffoldStarkAppWithProviders.tsx#L49C1-L52C6) to `~~/services/web3/connectors` , and filter connectors using the corresponding target network that is fetched from [`scaffold.config.ts`](https://github.com/Quantum3-Labs/scaffold-stark-2/blob/bb59cf4e0cfe0b4881104368288a1b5447224787/packages/nextjs/scaffold.config.ts#L12)

### Instructions for Contributing

- Leave a comment on this Issue.
- Wait for our confirmation to start on the project.
- Once you have received confirmation, begin working on your contribution.

### Incentives

Contributions are incentivized via Only Dust.

### Contact

For questions, join to our [tg group](https://t.me/+wO3PtlRAreo4MDI9) and reach out our team

### PR DESCRIPTION
**Pull request by danielcdz**
# Correctly display available wallet connectors

Fixes #156 

## Types of change

- [ ] Feature
- [ ] Bug
- [x] Enhancement

### CODE REVIEW

**Comment by Nadai2010** [comment]
Hello, I receive an error because I am not on the correct network, you must adjust scaffold.config.ts like this or similar.

Captura desde 2024-07-13 18-01-19
Captura desde 2024-07-13 18-01-42

You should also add the random option that was added in this PR #152 .

**Comment by danielcdz** [comment]
@Nadai2010 issue in comparison has been fixed, random results have been added, and linter issues have been fixed!

**Comment by Nadai2010** [comment]
@danielcdz  I have tested it and everything is fine. Thank you

**Review by Nadai2010 — APPROVED** [review]

**Comment by gianalarcon** [comment]
@danielcdz Thank you so much for your contribution.  Please send a DM to my tg @gianmalarcon

**Comment by danielcdz** [comment]
@Nadai2010 @gianalarcon Thank you for the opportunity!

**Pull request merged**
