### PR TITLE
refactor: use useScaffoldReadContract in ContractReadMethods

### LINKED ISSUE #229: Abstract all login on Debug Page to Scaffold Hooks
## Issue Overview

Currently Debug Page uses Starknet React hooks. Considering to use Scaffold Stark hooks instead so that we can unify and sync the functionality of the debug page and the scaffold hooks. 

## Proposed Solutions or Ideas

- Refactor the ReadOnlyFunctionForm, ContractVariables, and WriteOnlyFunctionForm reading hooks into scaffold hooks
- Include parsing on scaffold hooks
- Introduce an optional parsing flag to give the users more freedom on parsing the input data
- Add documentation regarding feature changes

### PR DESCRIPTION
**Pull request by metalboyrick**
# Task name here

Fixes #229 

## Types of change

- [ ] Feature
- [ ] Bug
- [X] Enhancement

## Comments (optional)

Nice to have - use context API to prevent prop drilling on some cases

### CODE REVIEW

**Comment by metalboyrick** [comment]
NOTE: latest commit is breaking

**Comment by metalboyrick** [comment]
@jrcarlos2000 for the write part, im a bit in doubt on whether we should use `useScaffoldWriteContract` since it involves manual parsing from string to rawArgs (this is in v2, in v3 this problem has been handled witha new parsing logic). What do you think?

**Comment by metalboyrick** [comment]
So far can successfully migrate read, but struggling a bit with write. Also, do we want to handle this in v3 or v2? if v3 i will close this PR and create a new one

**Comment by jrcarlos2000** [comment]
> NOTE: latest commit is breaking

i think v3 of `starknet-react` already supports some parsing of arguments, so it would be better to have this done on the v3 branch, rather than our current. Otherwise it will become a loop when we migrate to the new one.

**Comment by metalboyrick** [comment]
will perform changes on v3 branch

**Comment by metalboyrick** [comment]
closed due to moving changes to v3

**Pull request closed without merging**
